# Generated by Django 3.2.3 on 2021-05-28 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumesModel',
            fields=[
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='ID работника')),
                ('title', models.CharField(default='В поисках работы', max_length=64, verbose_name='Название')),
                ('work_experience', models.CharField(max_length=16, verbose_name='Опыт работы')),
                ('specialization', models.TextField(verbose_name='Специальность')),
                ('desired_salary', models.IntegerField(blank=True, verbose_name='Желаемая зарплата')),
                ('hard_skills', models.TextField(verbose_name='Ключевые навыки')),
                ('about_you', models.TextField(verbose_name='О себе')),
                ('native_language', models.TextField(verbose_name='Родной язык')),
                ('foreign_language', models.TextField(verbose_name='Иностранный язык')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('counter', models.IntegerField(default=0, verbose_name='Просмотрело')),
                ('is_moderated', models.BooleanField(blank=True, default=False, verbose_name='Прошла модерацию')),
                ('is_deleted', models.BooleanField(blank=True, default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-work_experience', 'desired_salary'],
            },
        ),
        migrations.CreateModel(
            name='VacanciesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=32, verbose_name='Название фирмы')),
                ('title', models.CharField(default='В поисках сотрудника', max_length=64, verbose_name='Название')),
                ('position', models.CharField(max_length=20, verbose_name='Должность')),
                ('salary', models.CharField(max_length=100, verbose_name='Предлагаемая зарплата')),
                ('requirements', models.TextField(verbose_name='Требования к работнику')),
                ('working_conditions', models.TextField(verbose_name='Условия работы')),
                ('work_experience', models.CharField(max_length=15, verbose_name='Опыт работы')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес фирмы')),
                ('date_publication', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('trash', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Оценка вакансии (1 - плохо, 10 - очень хорошо)')),
                ('counters', models.IntegerField(blank=True, default=0, verbose_name='Сколько просмотров')),
            ],
            options={
                'verbose_name': 'Вакансию',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-trash'],
            },
        ),
    ]
