# Generated by Django 3.2.3 on 2021-05-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210528_1309'),
        ('work', '0003_remove_resumesmodel_test_field'),
    ]

    operations = [
    ]
