# Generated by Django 3.1.7 on 2021-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_vacanciesmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
