# Generated by Django 3.2 on 2021-06-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0008_auto_20210530_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesmodel',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ID работника'),
        ),
    ]
